version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: hackme
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo:/data/db
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: hackme
    ports:
      - 8081:8081
    logging:
      driver: none
    depends_on:
      - mongo
